# config mysql (equivalente au contenu de config.DataSourceConfig.java)
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${DATABASE_ADDRESS}:${DATABASE_PORT}/${DATABASE_NAME}?createDatabaseIfNotExist=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver