server:
  port: 8081

spring:
  profiles:
    active: mysql


#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#  datasource:
#    url: jdbc:h2:mem:data
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2
#
